name: Windows Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          pip install -r test_requirements.txt
          pip install -e ".[d]"
          pre-commit install

      - name: Run tests with tox
        run: |
          .venv\Scripts\activate
          tox -e py
