name: Windows Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone additional repository
        run: |
          git clone https://github.com/Mr-Sunglasses/black.git additional_repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv\Scripts\activate
          python -m pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          if exist test_requirements.txt (pip install -r test_requirements.txt)
          pip install -e ".[d]"
          python -m pip install pre-commit

      - name: Install pre-commit hooks
        run: |
          .venv\Scripts\activate
          pre-commit install

      - name: Run tests with tox
        run: |
          .venv\Scripts\activate
          tox -e py
