name: Windows Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone additional repository
        run: git clone https://github.com/Mr-Sunglasses/black.git additional_repo

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          if (Test-Path test_requirements.txt) { pip install -r test_requirements.txt }
          pip install -e ".[d]"
          python -m pip install pre-commit

      - name: Install pre-commit hooks
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          pre-commit install

      - name: Run tests with tox
        shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          tox -e py
